main:
  - name: Organización
    identifier: schedule
    url: /schedule/
    weight: 1
  - name: Planificación
    parent: schedule
    url: /schedule/
    weight: 1
  - name: Syllabus
    parent: schedule
    url: /syllabus/
    weight: 2
  - name: Clases
    url: /content/
    weight: 3
  - name: Prácticos
    url: /example/
    weight: 4
  - name: Recursos
    url: /resource/
    weight: 6
  - name: '<i class="fab fa-slack"></i>'
    url: "https://join.slack.com/t/learn-r-udp/shared_invite/zt-11aaxe28l-FLhjoKOLcYrwD0OX0_LnKg"
    weight: 7
  - name: '<i class="fab fa-r-project"></i>'
    url: https://rstudio.cloud/
    weight: 9

content:
  - name: Información general
    weight: 1
  - name: Contenido
    weight: 2
example:
  - name: Información general
    weight: 1
  - name: Datos
    weight: 2
  - name: Ejemplos
    weight: 3
assignment:
  - name: Información general
    weight: 1
  - name: Other projects
    weight: 2
  - name: Tareas
    weight: 3
  - name: Evaluation
    weight: 4
resource:
  - name: Recursos
    weight: 1
  - name: Otros materiales
    weight: 3
  - name: Tutoriales
    weight: 2
